apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-deployment
        image: abifol/note-app:V5.1.2
        volumeMounts:
        - mountPath: /mnt/data/docker
          name: demo-pv
  volumes:
    - name: demo-pv
      persistentVolumeClaim:
        claimName: demo-pv
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
