apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app-deployment
        image: abifol/note-app:v2
        volumeMounts:
        - mountPath: /var/lib/docker/volumes/data/_data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: volume-claim
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
