name: Deploy Docker Image CI

on:
  workflow_dispatch

env:
  DOCKER_VERSION: V6.2.3

jobs:

  deploy:
    environment:
     name: production
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    - name: Deploy the Docker image
      run: |
          cd /home/master/actions-runner/_work/notes-app-cicd/notes-app-cicd
          pwd
          sudo kubectl get pods -A
          sudo kubectl apply -f deployment.yaml && kubectl apply -f service.yaml
          sudo kubectl get pods -A
